"""FastAPI dashboard for piptheory.

Routes:
  GET  /                         dashboard, latest run
  GET  /run/{date}               specific run (e.g. 2026-05-07)
  POST /api/chat                 chat completion (JSON in/out)
  POST /api/run                  trigger pipeline; returns PID
  GET  /api/run/status           is a manual run currently in progress?
  GET  /static/*                 css/js
"""
from __future__ import annotations

import json
import os
import re
import secrets
import subprocess
import sys
from datetime import datetime
from pathlib import Path

from fastapi import FastAPI, Form, HTTPException, Request
from fastapi.responses import HTMLResponse, JSONResponse, RedirectResponse, Response
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates
from pydantic import BaseModel

# Make src/ importable
APP_ROOT = Path(__file__).resolve().parent
PROJECT_ROOT = APP_ROOT.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from dashboard.loader import (  # noqa: E402
    INSTRUMENT_DISPLAY,
    InstrumentBias,
    Run,
    TradabilityFilterCard,
    display_label,
    display_name,
    list_runs,
    load_run,
    platform_symbol,
)
from src.config import BIAS_CARDS_DIR, ROOT  # noqa: E402
from src.data import (  # noqa: E402
    load_recent_events,
    regime as regime_mod,
    score_history,
    thesis_tracker,
    upcoming_events,
)
from src.data.prices import INSTRUMENT_TO_TICKER  # noqa: E402
from src.data.currency_strength import (  # noqa: E402
    all_history as cs_all_history,
    load_latest as cs_load_latest,
)
from src.data.price_strength import load_price_strength  # noqa: E402
from src.orchestration.pipeline import ACTIVE_UNIVERSE  # noqa: E402  single source of truth

# Public release: no position tracking, no chat, no manual events writes, no
# pipeline triggers. Personal-mode code paths removed when the project
# pivoted to a public read-only research site (see commit history for the
# original personal-use implementation, including PositionStore, advisor,
# advise_position, OpenRouterClient chat handler, /api/run trigger, etc.).

app = FastAPI(title="PIPTHEORY")
templates = Jinja2Templates(directory=str(APP_ROOT / "templates"))
app.mount("/static", StaticFiles(directory=str(APP_ROOT / "static")), name="static")


# Cache-busting version string for /static/* references in templates.
# Computed once per process restart from the most-recent mtime in the
# static directory. After a deploy that touches CSS/JS, the version
# string changes, so cached browsers re-fetch instead of serving stale
# code. The previous bug — user's mobile browser cached the old app.js
# from before the dashboard rebuild and silently broke chat/run buttons
# — is exactly what this prevents.
def _compute_static_version() -> str:
    static_dir = APP_ROOT / "static"
    try:
        mtimes = [p.stat().st_mtime for p in static_dir.rglob("*") if p.is_file()]
        return str(int(max(mtimes))) if mtimes else "0"
    except Exception:
        return "0"


_STATIC_VERSION = _compute_static_version()
templates.env.globals["static_version"] = _STATIC_VERSION

# Google Analytics 4 — the GA Measurement ID is public (it appears in page
# source). Hardcoded so it renders correctly on Render, the Cloudflare static
# build, and locally, independent of any stale GA_MEASUREMENT_ID env value.
_GA_ID = "G-0TYLNLEDEK"
templates.env.globals["ga_id"] = _GA_ID


def _load_ad_config() -> dict:
    """Read data/ad_config.yaml for ad-slot configuration. Empty/missing
    config is fine — templates render a tasteful placeholder."""
    import yaml as _yaml_mod
    path = PROJECT_ROOT / "data" / "ad_config.yaml"
    if not path.exists():
        return {}
    try:
        return _yaml_mod.safe_load(path.read_text(encoding="utf-8")) or {}
    except Exception:
        return {}


# Loaded once at startup. Restart uvicorn after editing data/ad_config.yaml
# to pick up the new IDs.
_AD_CONFIG = _load_ad_config()
templates.env.globals["ad_config"] = _AD_CONFIG

CONTEXT_CONVICTION_THRESHOLD = 7


# ---------- helpers for templates ----------

def _categorise_filter(run: Run) -> dict:
    """Filter cards no longer generated by the pipeline (Layer 4b skipped
    in the public release). Function retained as a no-op so any older
    template snippet referencing it doesn't crash; returns empty buckets."""
    return {"tradable": [], "watch": [], "passed": []}


def _hero_state(run: Run, by_verdict: dict) -> dict:
    """Returns hero card content + status class."""
    if by_verdict["tradable"]:
        n = len(by_verdict["tradable"])
        names = ", ".join(
            f"{c.instrument} ({display_label(c.instrument)})"
            for c in by_verdict["tradable"]
        )
        return {
            "status": "tradable",
            "eyebrow": "Today's brief",
            "headline": f"{n} setup{'s' if n != 1 else ''} ready: {names}",
            "subline": (
                "These have cleared structural review. The macro view is supported "
                "and the price location is favorable. Your call on whether to take "
                "any of them. See cards below for direction, levels, and invalidation."
            ),
        }
    if run.tradability:
        n_w = len(by_verdict["watch"])
        n_p = len(by_verdict["passed"])
        return {
            "status": "standby",
            "eyebrow": "Today's brief",
            "headline": "Stand aside — no setups at clean locations",
            "subline": (
                f"{n_w} on watch · {n_p} passed despite bias. "
                "No instrument in the active universe is at a tradable price location. "
                "This is the expected outcome on most days. Cash is a position."
            ),
        }
    if run.layer5_pm_brief:
        return {
            "status": "standby",
            "eyebrow": "Today's brief",
            "headline": "PM brief available — no Tradability Filter",
            "subline": "This run completed without Tradability Filter outputs. Read the brief below.",
        }
    return {
        "status": "standby",
        "eyebrow": "Today's brief",
        "headline": "No actionable setups in the active universe",
        "subline": (
            "No instrument met the conviction threshold today. Stand aside. "
            "Use the Inspect tab to see the underlying analysis."
        ),
    }


def _bias_for(run: Run, instrument: str) -> InstrumentBias | None:
    return next((b for b in run.instrument_biases if b.instrument == instrument), None)


def _conviction_class(conviction: int) -> str:
    if conviction >= 7:
        return "high"
    if conviction >= 4:
        return "med"
    return "low"


def _priority_class(priority: str) -> str:
    return {"A+": "aplus", "A": "a", "B": "b", "C": "c"}.get(priority, "")


def _verdict_label(verdict: str) -> str:
    return {
        "tradable_now": "Tradable now",
        "watch": "Watch",
        "pass_despite_bias": "Passed",
        "skip_no_data": "No data",
        "below_threshold": "Below threshold",
        "unparseable": "Unparseable",
    }.get(verdict, verdict)


import yaml as _yaml

_FILTER_YAML_BLOCK_RE = re.compile(
    r"```ya?ml\s*\n(.*?)\n```", re.DOTALL | re.IGNORECASE,
)

# Fallback regexes if the agent didn't wrap output in a yaml fence.
# The first form catches plain `verdict_reason: text` (single line, possibly
# quoted). The folded `verdict_reason: >` and literal `|` block scalars are
# handled by the YAML parser path; if that fails we still try a multi-line
# regex fallback that tolerates indented continuation lines.
_VERDICT_REASON_PLAIN_RE = re.compile(
    r"verdict_reason:\s*[\"']([^\"'\n]+)[\"']", re.IGNORECASE,
)
# Inline unquoted bare scalar — value continues to end-of-line. Used when the
# agent emits `verdict_reason: Applied swing rules: price...` without quotes.
# Such input fails YAML's mapping parser (the colon in the value looks like a
# nested mapping), so we need a regex that doesn't depend on YAML.
# The negative lookahead `(?![>|\s\n])` excludes the folded/literal markers
# `>` and `|` and empty values — those use the multi-line block path.
_VERDICT_REASON_INLINE_RE = re.compile(
    r"verdict_reason:[ \t]+(?![>|\s\n])([^\n]+)", re.IGNORECASE,
)
_VERDICT_REASON_BLOCK_RE = re.compile(
    r"verdict_reason:\s*[>|]?\s*\n((?:[ \t]+[^\n]+\n?)+)", re.IGNORECASE,
)
_HUMAN_NOTES_RE = re.compile(
    r"human_review_notes:\s*\|?\s*\n((?:[ \t]+[^\n]*\n?)+)", re.IGNORECASE,
)


def _parse_filter_yaml(filter_md: str) -> dict:
    """Best-effort: extract the YAML block from a filter card and parse it.

    The Filter agent's prompt asks for a fenced ```yaml block. Most outputs
    follow that. Some don't, so we fall back gracefully — caller checks
    for an empty dict.
    """
    if not filter_md:
        return {}
    m = _FILTER_YAML_BLOCK_RE.search(filter_md)
    if not m:
        return {}
    try:
        data = _yaml.safe_load(m.group(1))
        return data if isinstance(data, dict) else {}
    except _yaml.YAMLError:
        return {}


def _filter_field(filter_md: str, key: str) -> str:
    """Extract a single field from a filter card. Tries YAML parse first,
    then plain-text regex, then block-scalar regex. Returns trimmed string
    or empty."""
    parsed = _parse_filter_yaml(filter_md)
    if parsed and isinstance(parsed.get(key), str):
        return parsed[key].strip()
    if key == "verdict_reason":
        # Try quoted single-line first (cleanest), then unquoted inline,
        # then folded/literal block scalar.
        m = _VERDICT_REASON_PLAIN_RE.search(filter_md or "")
        if m:
            return m.group(1).strip()
        m = _VERDICT_REASON_INLINE_RE.search(filter_md or "")
        if m:
            return m.group(1).strip()
        m = _VERDICT_REASON_BLOCK_RE.search(filter_md or "")
        if m:
            return " ".join(ln.strip() for ln in m.group(1).strip().splitlines()).strip()
    if key == "human_review_notes":
        m = _HUMAN_NOTES_RE.search(filter_md or "")
        if m:
            return " ".join(ln.strip() for ln in m.group(1).strip().splitlines()).strip()
    return ""
_STRATEGIST_NOTES_RE = re.compile(
    r"NOTES?:?\**\s*([^\n*]+(?:\n(?!#|\*\*)[^\n]+)*)", re.IGNORECASE,
)
# Judge's "JUDGMENT REASONING (3-5 sentences):" block — the substantive macro
# story explaining WHY the bias is what it is. Captures the lines that follow
# the heading until a blank line or the next ALL-CAPS section header.
# Tolerates markdown emphasis (**JUDGMENT REASONING:**), trailing spaces,
# and parenthetical asides ("(3-5 sentences)") between the label and colon.
_JUDGE_REASONING_RE = re.compile(
    r"\**\s*JUDGMENT\s+REASONING[^\n:]*:\**\s*\n+"
    r"((?:.+?\n?)+?)(?=\n\s*\n|\n\**\s*[A-Z][A-Z ]+(?:[:(]|\s*\n)|\Z)",
    re.IGNORECASE,
)
_JUDGE_PRIMARY_THEME_RE = re.compile(
    r"PRIMARY\s*THEME[^:]*:\s*([^\n]+)", re.IGNORECASE,
)
_STRATEGIST_PRIMARY_RE = re.compile(
    r"Primary[\s:\-]+([^\n]+)", re.IGNORECASE,
)
_DRIVING_THEMES_RE = re.compile(
    r"DRIVING\s*THEMES?[^\n]*\n((?:[^\n]*\n){1,4})", re.IGNORECASE,
)


def _first_sentence(text: str, max_chars: int = 240) -> str:
    """First sentence of a paragraph, truncated to max_chars.

    Sentences end at `. ` or `.<newline>` or end-of-text. Em/en dashes inside
    a sentence don't count as terminators. If the first 'sentence' is longer
    than max_chars, hard-truncate at a word boundary.
    """
    text = re.sub(r"\s+", " ", text).strip()
    # First sentence: up to first period followed by space or end-of-string.
    m = re.search(r"^(.+?\.)(?:\s|$)", text)
    if m:
        first = m.group(1).strip()
    else:
        first = text
    if len(first) > max_chars:
        cut = first[:max_chars].rsplit(" ", 1)[0]
        first = cut + "…"
    return first


def _extract_macro_summary(b: InstrumentBias, co) -> str:
    """One-sentence macro driver summary: why is the bias what it is?

    Priority (best content first):
      1. Judge's JUDGMENT REASONING first sentence — substantive macro story
      2. Judge's PRIMARY THEME line (label only — fallback when reasoning
         block can't be extracted)
      3. Strategist's first 'Primary:' theme line
      4. Strategist DRIVING THEMES block (first line)
      5. Bias direction + conviction (composed fallback)
    """
    if co and co.judge:
        m = _JUDGE_REASONING_RE.search(co.judge)
        if m:
            block = m.group(1).strip()
            # Drop leading bullet/numbering noise and markdown emphasis chars
            block = re.sub(r"^[-*#>•\s]+", "", block).lstrip()
            block = block.replace("**", "").replace("*", "")
            first = _first_sentence(block, max_chars=260)
            if 30 <= len(first) <= 260:
                return f"Macro: {first}"

        m = _JUDGE_PRIMARY_THEME_RE.search(co.judge)
        if m:
            theme = m.group(1).strip().strip("[]").rstrip(".")
            if 5 <= len(theme) <= 200:
                return f"Macro: {theme}."

    if b.raw_section:
        m = _STRATEGIST_PRIMARY_RE.search(b.raw_section)
        if m:
            theme = m.group(1).strip().strip("*").rstrip(".")
            if 5 <= len(theme) <= 200:
                return f"Macro: {theme}."
        m = _DRIVING_THEMES_RE.search(b.raw_section)
        if m:
            first = m.group(1).strip().split("\n")[0].strip()
            first = re.sub(r"^[-*•\s]+", "", first).rstrip(".")
            if 5 <= len(first) <= 200:
                return f"Macro: {first}."

    return f"Macro: {b.bias.capitalize()} bias at {b.conviction}/10."


def _extract_chart_summary(filter_card, has_council: bool) -> str:
    """One-sentence chart status: what did structural review say?

    Priority:
      1. Filter's verdict_reason (when filter ran) — via YAML parser, with
         regex fallbacks for unfenced or malformed output
      2. Filter's human_review_notes first sentence
      3. 'Council ran but no filter' (transitional state)
      4. 'Below council threshold' (no review at all)
    """
    if filter_card and filter_card.raw:
        reason = _filter_field(filter_card.raw, "verdict_reason")
        if reason:
            return f"Chart: {reason.rstrip('.')}."
        notes = _filter_field(filter_card.raw, "human_review_notes")
        if notes:
            first = notes.split(". ")[0].strip().rstrip(".")
            if first and len(first) < 240:
                return f"Chart: {first}."
        # Sub-threshold instruments produce a `note:` field instead of a
        # verdict — surface that rather than "unparseable" if it's there.
        note = _filter_field(filter_card.raw, "note")
        if note:
            first = note.split(". ")[0].strip().rstrip(".")
            if first and len(first) < 240:
                return f"Chart: {first}."
        return "Chart: filter output unparseable."

    if has_council:
        return "Chart: structural review pending for this run."
    return "Chart: not reviewed (conviction below council threshold)."


def _summarise_card(b: InstrumentBias, filter_card, in_active: bool, council_output=None) -> str:
    """Two-part 'macro + chart' summary. Macro always comes first because
    it's the primary signal source (chart only gates timing)."""
    macro = _extract_macro_summary(b, council_output)
    chart = _extract_chart_summary(filter_card, has_council=council_output is not None)
    return f"{macro} {chart}"


def _build_unified_watchlist(run: Run) -> list[dict]:
    """One ranked list of all instruments. Authoritative conviction = Judge if
    available, else Strategist. Each row carries a single answer per field."""
    rows: list[dict] = []
    for b in run.instrument_biases:
        co = run.council.get(b.instrument)
        if co and co.judge_conviction:
            final_conv = co.judge_conviction
            final_bias = (co.judge_bias or b.bias).lower() or "no view"
        else:
            final_conv = b.conviction
            final_bias = b.bias.lower() or "no view"

        in_active = b.instrument in ACTIVE_UNIVERSE
        filter_card = run.tradability.get(b.instrument)
        verdict = filter_card.verdict if filter_card else None

        # Actionability tier.
        # Two principles:
        #   (a) Filter verdict ALWAYS wins over conviction — if structural
        #       review said skip, it's collapsed regardless of macro conviction.
        #   (b) Conviction < 5 ALWAYS collapses, even if Filter said watch.
        #       This is the defensive layer in case the pipeline lets a
        #       sub-threshold case slip through to the Filter agent.
        # Visibility: tiers 0-2 visible (cards), 3-4 collapsed (compact list).
        if final_conv < 5 and verdict not in ("tradable_now",):
            # Sub-threshold conviction — collapse regardless of Filter verdict.
            # tradable_now is the one carve-out: if the Filter genuinely thinks
            # the chart is so clean that conviction can be revisited, surface it.
            tier, tier_label = 4, "low_conv"
        elif verdict == "tradable_now":
            tier, tier_label = 0, "tradable_now"
        elif verdict == "watch":
            tier, tier_label = 1, "watch"
        elif verdict == "pass_despite_bias":
            tier, tier_label = 3, "passed"
        elif verdict == "below_threshold":
            tier, tier_label = 4, "low_conv"
        elif final_conv >= 6:
            tier, tier_label = 2, "high_conv_no_filter"  # high conv but no filter ran
        else:
            tier, tier_label = 4, "low_conv"

        # Single pill label (plain English).
        # Sub-threshold conviction (<5) is the dominant fact; the Filter
        # verdict is suppressed in the pill because the structural review
        # shouldn't have been treated as authoritative on a thin macro view.
        # tradable_now is the carve-out — if the chart is exceptionally clean
        # we still surface it.
        if verdict == "tradable_now":
            pill_text = "Tradable now"
            pill_class = "tradable"
        elif final_conv < 5:
            pill_text = "Low conviction"
            pill_class = "neutral"
        elif verdict == "watch":
            pill_text = "Watch"
            pill_class = "watch"
        elif verdict == "pass_despite_bias":
            pill_text = "Skip"
            pill_class = "passed"
        elif final_conv >= 6:
            pill_text = "Worth a look"
            pill_class = "watch"
        else:
            pill_text = "Low conviction"
            pill_class = "neutral"

        # Short one-line explanation for the compact 'Other' row.
        # Priority:
        #   1. Filter's verdict_reason — if a structural review happened,
        #      use what it concluded (informative regardless of verdict).
        #   2. Sub-threshold conviction message
        #   3. Generic per-verdict fallback
        simple_summary = ""
        if filter_card and filter_card.raw:
            reason = _filter_field(filter_card.raw, "verdict_reason")
            if reason:
                simple_summary = reason.rstrip(".") + "."
        if not simple_summary:
            if final_conv < 5:
                simple_summary = (
                    f"Low conviction ({final_conv}/10). Macro signal isn't "
                    f"strong enough to justify a structural review."
                )
            elif verdict == "pass_despite_bias":
                simple_summary = (
                    "Macro view supports this, but the chart is against it "
                    "right now (counter-trend, fuzzy invalidation, or blocking event)."
                )
            else:
                simple_summary = f"{final_bias.capitalize()}, but no clear setup yet."

        rows.append({
            "symbol": b.instrument,
            "name": display_label(b.instrument),
            "platform": platform_symbol(b.instrument),
            "platform_differs": platform_symbol(b.instrument) != b.instrument,
            "bias": final_bias,
            "conviction": final_conv,
            "conviction_class": _conviction_class(final_conv),
            "summary": _summarise_card(b, filter_card, in_active, council_output=co),
            "simple_summary": simple_summary,
            "in_active": in_active,
            "has_council": co is not None,
            "has_filter": filter_card is not None,
            "verdict": verdict or "",
            "pill_text": pill_text,
            "pill_class": pill_class,
            "tier": tier,
            "tier_label": tier_label,
        })

    rows.sort(key=lambda r: (r["tier"], -r["conviction"], r["symbol"]))
    return rows


# ===========================================================================
# NEW HOME-VIEW CONTEXT BUILDERS
# Used by the redesigned single-page dashboard (desktop + mobile surfaces).
# Each builder returns plain-dict data — templates do display only, no logic.
# ===========================================================================

# Strength label for an integer conviction. Bands, not digits — the UI shows
# "moderate" for a 6 and a 7 because they're the same band; numeric value is
# also shown for users who want it.
def _strength_band(conviction: int) -> str:
    if conviction >= 8: return "strong"
    if conviction >= 6: return "moderate"
    if conviction >= 5: return "weak"
    return "trash"


def _strength_label(conviction: int) -> str:
    return {
        "strong": "Strong",
        "moderate": "Moderate",
        "weak": "Weak",
        "trash": "Very weak",
    }.get(_strength_band(conviction), "Unknown")


def _normalise_dir_word(bias: str) -> str:
    b = (bias or "").lower()
    if "long" in b or "bull" in b: return "long"
    if "short" in b or "bear" in b: return "short"
    return "no view"


# ─── TODAY: actions + ideas ─────────────────────────────────────────────────

def _build_today_block(run: Run) -> dict:
    """The 'TODAY' panel for the public research site: the top high-
    conviction macro reads. No positions, no chart filter — just the
    Council Judge's verdict per instrument.

    Returns: {"ideas": [...]}. The `actions` key (open-trade alerts in
    the old personal build) is no longer populated; kept as an empty
    list so any older template snippet referencing it still renders.
    """
    candidates: list[dict] = []
    for b in run.instrument_biases:
        co = run.council.get(b.instrument)
        if co and co.judge_conviction:
            conv = co.judge_conviction
            bias_raw = co.judge_bias or b.bias
        else:
            conv = b.conviction
            bias_raw = b.bias
        direction = _normalise_dir_word(bias_raw)
        if direction == "no view" or conv < 6:
            # Public site: surface only moderate-or-better macro reads
            continue

        macro_summary = _extract_macro_summary(b, co).removeprefix("Macro: ").strip()
        candidates.append({
            "kind": "idea",
            "instrument": b.instrument,
            "name": display_label(b.instrument),
            "direction": direction,
            "conviction": conv,
            "strength_band": _strength_band(conv),
            "strength_label": _strength_label(conv),
            "macro_summary": macro_summary,
        })
    candidates.sort(key=lambda c: (-c["conviction"], c["instrument"]))
    ideas = candidates[:4]  # show top 4 max
    return {"actions": [], "ideas": ideas}


def _action_word(action: str) -> str:
    return {
        "hold": "Hold",
        "review": "Review",
        "trim": "Trim",
        "trail_stop": "Trail stop",
        "close": "Close",
        "emergency_close": "Emergency close",
    }.get(action, action.title())


def _action_class(action: str) -> str:
    """Return 'urgent' (red), 'attention' (amber), or '' for the action."""
    if action in ("emergency_close", "close"): return "urgent"
    if action in ("trim", "trail_stop", "review"): return "attention"
    return ""


# ─── MACRO PICTURE ──────────────────────────────────────────────────────────

_THEME_HEADING_RE = re.compile(
    r"^###\s+\d+\.\s+(.+?)\s+[—–-]\s+Conviction\s+(\d+)\s*/\s*10",
    re.MULTILINE,
)
_REGIME_HEADER_RE = re.compile(
    r"##\s*Regime\s*Snapshot\s*\n+\*\*([^*]+)\*\*",
    re.IGNORECASE,
)


def _build_macro_block() -> dict:
    """Parse THEMES.md into a structured block: regime headline + ranked theme
    list + next catalyst.
    """
    themes_path = PROJECT_ROOT / "docs" / "THEMES.md"
    if not themes_path.exists():
        return {"regime": "", "themes": [], "next_catalyst": "", "days_to_catalyst": None}
    text = themes_path.read_text(encoding="utf-8")

    # Regime headline
    regime = ""
    m = _REGIME_HEADER_RE.search(text)
    if m:
        regime = m.group(1).strip().rstrip(".")
        # Trim long regime lines to one sentence for the panel
        regime = regime.split(". ")[0].rstrip(".") + "."

    # Themes
    themes = []
    for tm in _THEME_HEADING_RE.finditer(text):
        name = tm.group(1).strip()
        conv = int(tm.group(2))
        themes.append({"name": name, "conviction": conv, "pct": conv * 10})
    themes.sort(key=lambda t: -t["conviction"])

    # Next catalyst from events.yaml — first HIGH-severity event in next 14 days
    try:
        events = upcoming_events(days_ahead=14, min_severity="high")
    except Exception:
        events = []
    next_catalyst = ""
    days_to_catalyst = None
    if events:
        ev = events[0]
        days_to_catalyst = ev.days_from_today
        date_str = ev.date.strftime("%b %d")
        next_catalyst = f"{date_str} — {ev.name}".strip(" —")
    return {
        "regime": regime,
        "themes": themes[:6],
        "next_catalyst": next_catalyst,
        "days_to_catalyst": days_to_catalyst,
    }


# ─── ALL INSTRUMENTS TABLE ──────────────────────────────────────────────────

def _build_instruments_table(run: Run, open_instruments: set[str] | None = None) -> list[dict]:
    """One row per instrument. Public-release version: state copy is
    macro-only (no chart/filter verdicts). open_instruments is unused
    in the public site but kept in the signature for back-compat with
    older callers.
    """
    open_instruments = open_instruments or set()
    # Pull primary theme out of each judge.md if present so we can show
    # which theme drives each instrument. Format:
    #   "PRIMARY THEME (from THEMES.md): <theme name>"
    _PRIMARY_THEME_RE = re.compile(
        r"PRIMARY\s+THEME[^:\n]*:\**\s*\**\s*([^\n*]+)",
        re.IGNORECASE,
    )

    rows: list[dict] = []
    for b in run.instrument_biases:
        co = run.council.get(b.instrument)
        if co and co.judge_conviction:
            conv = co.judge_conviction
            bias_raw = co.judge_bias or b.bias
        else:
            conv = b.conviction
            bias_raw = b.bias
        direction = _normalise_dir_word(bias_raw)

        # Macro-only state copy + tier band. Tiers drive the visual split
        # in the dashboard between "high-conviction" (featured cards),
        # "developing" (compact rows), and "below the bar" (de-emphasized).
        if conv >= 8:
            state, state_class, tier_band = "Strong macro read", "good", "high"
        elif conv >= 7:
            state, state_class, tier_band = "Solid macro read", "good", "high"
        elif conv >= 5:
            state, state_class, tier_band = "Developing read", "warn", "developing"
        elif conv >= 4:
            state, state_class, tier_band = "Watch only", "neutral", "watch"
        else:
            state, state_class, tier_band = "Below the bar", "neutral", "noise"

        # Primary theme — try judge file first, fall back to nothing
        primary_theme = ""
        if co and co.judge:
            if pm := _PRIMARY_THEME_RE.search(co.judge):
                primary_theme = pm.group(1).strip().split("(")[0].strip()
                # Some outputs slip a trailing comma or period
                primary_theme = primary_theme.rstrip(",.;:").strip()
                # Strip pipeline artifacts: "Candidate – ", trailing dashes, N/A
                primary_theme = re.sub(r"^(?:Candidate|Emerging)\s*[–—-]\s*", "", primary_theme, flags=re.IGNORECASE).strip()
                primary_theme = primary_theme.rstrip("–—- ").strip()
                if primary_theme.startswith("[N/A") or primary_theme.upper() == "N/A":
                    primary_theme = ""

        hist = score_history.summary_for(b.instrument, n=14)
        thesis = thesis_tracker.status_for(b.instrument)

        # ── Inline reasoning data for full-page cards ──────────────
        judge_raw = co.judge if co else ""
        bull_raw = co.bull if co else ""
        bear_raw = co.bear if co else ""

        # Extract structured fields from judge output
        _tf_m = re.search(r"TIMEFRAME[:\s]*([^\n]+)", judge_raw, re.I)
        timeframe = _tf_m.group(1).strip() if _tf_m else ""
        _pb = re.search(r"P\(bull[^)]*\)[:\s]*([\d.]+)%", judge_raw, re.I)
        _pe = re.search(r"P\(bear[^)]*\)[:\s]*([\d.]+)%", judge_raw, re.I)
        _ps = re.search(r"P\(sideways[^)]*\)[:\s]*([\d.]+)%", judge_raw, re.I)
        p_bull = float(_pb.group(1)) if _pb else 0
        p_bear = float(_pe.group(1)) if _pe else 0
        p_flat = float(_ps.group(1)) if _ps else max(0, 100 - p_bull - p_bear)

        # Extract bull thesis (1 sentence)
        _bt = re.search(r"THESIS[^:\n]*:\s*\n?\s*([^\n]+)", bull_raw, re.I)
        bull_thesis = _bt.group(1).strip() if _bt else ""

        # Extract bear thesis (1 sentence)
        _bet = re.search(r"THESIS[^:\n]*:\s*\n?\s*([^\n]+)", bear_raw, re.I)
        bear_thesis = _bet.group(1).strip() if _bet else ""

        # Extract judge narrative (after JUDGMENT REASONING:)
        _jn = re.split(r"JUDGMENT\s+REASONING\s*:?\s*\n?", judge_raw, flags=re.I)
        judge_narrative = _jn[-1].strip() if len(_jn) > 1 else judge_raw
        # Strip prompt artifacts like "(3-5 sentences):" echoed by LLMs
        judge_narrative = re.sub(
            r"^\s*\(\d+-\d+\s+sentences?\)\s*:?\s*\n?", "", judge_narrative
        ).strip()

        # Extract advocate narratives — strip metadata header, start from
        # PRIMARY DRIVER or SUPPORTING EVIDENCE (thesis shown separately)
        def _strip_advocate_header(raw: str) -> str:
            # Try to split at PRIMARY DRIVER or SUPPORTING EVIDENCE
            for marker in [r"PRIMARY\s+DRIVER", r"SUPPORTING\s+EVIDENCE",
                           r"KEY\s+ARGUMENTS?"]:
                parts = re.split(marker + r"\s*:?\s*\n?", raw, maxsplit=1, flags=re.I)
                if len(parts) > 1:
                    return marker.replace(r"\s+", " ").replace(r"\s*", "").replace(r":?\s*\n?", "").replace("\\", "") + ":\n" + parts[1]
            # Fallback: strip INSTRUMENT/ROLE/THESIS header lines
            lines = raw.split("\n")
            start = 0
            for i, ln in enumerate(lines):
                if re.match(r"^(INSTRUMENT|ROLE|THESIS)[:\s]", ln, re.I):
                    start = i + 1
                    continue
                if ln.strip() and start > 0:
                    break
            return "\n".join(lines[start:]).strip() if start > 0 else raw

        bull_narrative = _strip_advocate_header(bull_raw) if bull_raw else ""
        bear_narrative = _strip_advocate_header(bear_raw) if bear_raw else ""

        # Render HTML for each role
        judge_html = _render_markdown(_format_analysis_sections(judge_narrative))
        bull_html = _render_markdown(_format_analysis_sections(bull_narrative))
        bear_html = _render_markdown(_format_analysis_sections(bear_narrative))

        rows.append({
            "symbol": b.instrument,
            "name": display_label(b.instrument),
            "direction_raw": bias_raw,
            "direction": direction,
            "conviction": conv,
            "strength_band": _strength_band(conv),
            "strength_label": _strength_label(conv),
            "state": state,
            "state_class": state_class,
            "tier_band": tier_band,
            "primary_theme": primary_theme,
            "verdict": "",
            "is_open_position": False,
            "history": hist,
            "thesis": thesis,
            # Inline reasoning
            "timeframe": timeframe,
            "p_bull": p_bull,
            "p_bear": p_bear,
            "p_flat": p_flat,
            "bull_thesis": bull_thesis,
            "bear_thesis": bear_thesis,
            "judge_html": judge_html,
            "bull_html": bull_html,
            "bear_html": bear_html,
        })
    rows.sort(key=lambda r: (-r["conviction"], r["symbol"]))
    return rows


# ─── Regime cache ──────────────────────────────────────────────────────────
# Regime classification requires several FRED calls (industrial production,
# NFP, retail sales, claims, CPI, PCE, breakevens). Don't re-fetch on every
# page load. Cache for 6 hours — macro data updates monthly anyway, so
# refreshing 4x/day is more than enough.
_REGIME_CACHE: dict = {"read": None, "fetched_at": None}


def _get_regime() -> dict:
    from datetime import timedelta
    now = datetime.now()
    cached = _REGIME_CACHE.get("read")
    fetched = _REGIME_CACHE.get("fetched_at")
    if cached is not None and fetched is not None:
        if now - fetched < timedelta(hours=6):
            return cached
    try:
        read = regime_mod.classify_regime().to_dict()
        _REGIME_CACHE["read"] = read
        _REGIME_CACHE["fetched_at"] = now
        return read
    except Exception as e:
        # If FRED is down, fall back to cached if any, else return a
        # safe TRANSITION read so the dashboard still renders.
        if cached is not None:
            return cached
        return {
            "label": "TRANSITION",
            "growth_score": 0,
            "inflation_score": 0,
            "growth_indicators": [],
            "inflation_indicators": [],
            "implications": {},
            "error": str(e),
        }


# ─── HOME CONTEXT (the whole page) ──────────────────────────────────────────

def _detect_surface(request: Request) -> str:
    """Return 'mobile' or 'desktop'. Order of precedence:
      1. ?view=mobile|desktop query param (sticky via cookie)
      2. cookie
      3. user-agent (mobile UAs → mobile)
      4. desktop default

    The showcase surface was removed when the project went public — only
    desktop and mobile remain.
    """
    valid = ("mobile", "desktop")
    override = request.query_params.get("view")
    if override in valid:
        return override
    cookie = request.cookies.get("nam_view")
    if cookie in valid:
        return cookie
    ua = (request.headers.get("user-agent") or "").lower()
    mobile_markers = ("iphone", "android", "ipod", "mobile safari", "windows phone")
    if any(m in ua for m in mobile_markers):
        return "mobile"
    return "desktop"


_HEADLINE_BLOCK_RE = re.compile(
    r"^##\s+Headline\s*\n+(.+?)(?=\n\s*\n|\n##\s|\Z)",
    re.IGNORECASE | re.MULTILINE | re.DOTALL,
)
# The brief's own H1 (markdown `# ...` or setext `===` underline) is
# redundant with the page-level headline. Strip it so the rendered
# article body starts from the first H2, with no duplicated title.
_BRIEF_H1_ATX_RE = re.compile(r"^#\s+[^\n]+\n+", re.MULTILINE)
_BRIEF_H1_SETEXT_RE = re.compile(r"^[^\n#=]+\n=+\s*\n+", re.MULTILINE)
# Tidy up legacy headers from older brief output that still slip through.
# These get replaced with editorial-voice equivalents so older runs don't
# render with "tradable_now" / personal-trading jargon visible to readers.
_LEGACY_H2_REWRITES = [
    (re.compile(r"^##\s+1\.\s+Setups for review.*$", re.MULTILINE | re.IGNORECASE),
     "## What the data favors"),
    (re.compile(r"^##\s+2\.\s+Watch list.*$", re.MULTILINE | re.IGNORECASE),
     "## On watch"),
    (re.compile(r"^##\s+3\.\s+Passed despite bias.*$", re.MULTILINE | re.IGNORECASE),
     "## Passed today"),
    (re.compile(r"^##\s+What to watch in the next 24-48 hours.*$", re.MULTILINE | re.IGNORECASE),
     "## What we're watching next"),
    (re.compile(r"^##\s+Risk view.*$", re.MULTILINE | re.IGNORECASE),
     "## Risks"),
    (re.compile(r"^##\s+Confidence in this brief.*$", re.MULTILINE | re.IGNORECASE),
     "## Confidence"),
    (re.compile(r"^##\s+Executive summary.*$", re.MULTILINE | re.IGNORECASE),
     "## Today's read"),
]
# Lines from older briefs that leaked tactical / personal-trading content.
# We strip these line-by-line. The fresh PM prompt prevents them from being
# generated, but cached runs from before the prompt change can still hit
# the page until they're regenerated.
_LEAK_LINE_RES = [
    re.compile(r"^\s*-\s*Setup at:.*$", re.MULTILINE | re.IGNORECASE),
    re.compile(r"^\s*-\s*Key level to act around:.*$", re.MULTILINE | re.IGNORECASE),
    re.compile(r"^\s*-\s*Invalidation level:.*$", re.MULTILINE | re.IGNORECASE),
    re.compile(r"^\s*-\s*Target zone.*$", re.MULTILINE | re.IGNORECASE),
    re.compile(r"^\s*-\s*Entry zone.*$", re.MULTILINE | re.IGNORECASE),
    re.compile(r"\(tradable_now\)", re.IGNORECASE),
    re.compile(r"\(watch verdict\)", re.IGNORECASE),
]
_REGIME_TAGLINE_FALLBACK = {
    "GOLDILOCKS":  "Growth holds, inflation contained — risk assets in the sweet spot.",
    "REFLATION":   "Growth and inflation accelerating together — commodities and cyclicals lead.",
    "STAGFLATION": "Growth weakening while inflation lingers — the hardest mix for risk.",
    "DEFLATION":   "Growth and inflation both falling — yields decline, defensives lead.",
    "TRANSITION":  "Regime in flux — signals mixed between regimes. Await confirmation.",
}


def _extract_headline(brief_md: str, regime_label: str | None) -> tuple[str, str]:
    """Pull the headline out of the PM brief, clean the body.

    Returns (headline_text, body_md_without_headline_and_h1).

    1. Extract `## Headline` if present (new-prompt format).
       Fall back to regime tagline otherwise.
    2. Strip the brief's own H1 — it's redundant with the page headline.
    3. Rewrite legacy H2s ("1. Setups for review (tradable_now)" → "What
       the data favors", etc.) so older runs don't expose trading jargon.
    4. Drop "Setup at: $X" / "Invalidation level: $X" lines as defence
       against any cached output that still has them.

    The fresh-prompt path is clean and most of this cleanup is dead code.
    But pipeline outputs are immutable artifacts — older runs would still
    render badly without this post-processing.
    """
    if not brief_md:
        return (_REGIME_TAGLINE_FALLBACK.get(regime_label or "TRANSITION", ""), brief_md)

    # 1. Headline extraction
    m = _HEADLINE_BLOCK_RE.search(brief_md)
    if m:
        headline = " ".join(m.group(1).split()).strip().rstrip(".") + "."
        body = brief_md[:m.start()] + brief_md[m.end():]
    else:
        headline = _REGIME_TAGLINE_FALLBACK.get(regime_label or "TRANSITION", "")
        body = brief_md

    # 2. Strip the brief's own H1. Try ATX first (`# Title`), then setext
    # (`Title\n=====`). Only strips the FIRST occurrence so any H1 deeper
    # in the brief (unusual) survives.
    body = _BRIEF_H1_ATX_RE.sub("", body, count=1)
    body = _BRIEF_H1_SETEXT_RE.sub("", body, count=1)

    # 3. Rewrite legacy section headers
    for pat, replacement in _LEGACY_H2_REWRITES:
        body = pat.sub(replacement, body)

    # 4. Strip leaked tactical lines defensively
    for pat in _LEAK_LINE_RES:
        body = pat.sub("", body)

    # Collapse any triple+ blank lines created by the line removals
    body = re.sub(r"\n{3,}", "\n\n", body)

    return (headline, body.strip())


def _build_home_context(run: Run, runs: list[str], date: str, surface: str) -> dict:
    """Public release home context. No positions, no FTMO, no chat, no
    recent-events write surface. Pure read-only research data: today's
    high-conviction reads, macro themes, regime tag, full instrument
    table, the PM brief, and the relationship graph."""
    today = _build_today_block(run)
    macro = _build_macro_block()
    instruments = _build_instruments_table(run, open_instruments=set())
    regime = _get_regime()

    # Recent events log (read-only on the public site — surfaces what
    # the editor has logged but no UI to add/delete from the browser)
    try:
        recent_events_raw = load_recent_events()
    except Exception:
        recent_events_raw = []
    recent_events = [{
        "date": e.date.isoformat(),
        "days_ago": e.days_ago,
        "headline": e.headline,
        "impact": e.impact,
        "notes": e.notes,
        "relevance": e.relevance,
        "affects": e.affects or [],
    } for e in recent_events_raw[:10]]

    # Partial-run detection retained — we still want to know when the
    # Strategist's response was cut off so the public banner can say so.
    n_complete = len(run.instrument_biases)
    n_expected = len(ACTIVE_UNIVERSE)
    partial_run = n_complete < n_expected
    partial_msg = (
        f"Today's publication is partial — only {n_complete} of "
        f"{n_expected} instruments have full analysis. Tomorrow's "
        f"sync will regenerate."
    ) if partial_run else ""

    # Last-publication timestamp from the run's summary file mtime
    last_synced_iso = None
    try:
        summary_path = BIAS_CARDS_DIR / date / "run_summary.json"
        if summary_path.exists():
            last_synced_iso = datetime.fromtimestamp(
                summary_path.stat().st_mtime
            ).isoformat(timespec="seconds")
    except Exception:
        pass

    brief_raw = run.layer5_pm_brief or ""
    headline, brief_body = _extract_headline(
        brief_raw, regime.get("label") if regime else None,
    )

    # Upcoming events for the catalyst calendar on the dashboard.
    # Returns CalendarEvent objects within the lookahead window. Convert
    # to plain dicts for the template.
    try:
        upcoming_raw = upcoming_events(days_ahead=14, min_severity="low")
        upcoming_calendar = [e.to_dict() for e in upcoming_raw][:8]
    except Exception:
        upcoming_calendar = []

    return {
        "surface": surface,
        "run_date": date,
        "runs": runs,
        "today": today,
        "macro": macro,
        "regime": regime,
        "instruments": instruments,
        "upcoming_calendar": upcoming_calendar,
        "recent_events": recent_events,
        "partial_run": partial_run,
        "partial_msg": partial_msg,
        "brief_md": brief_body,
        "brief_headline": headline,
        "last_synced_iso": last_synced_iso,
        "active_universe": ACTIVE_UNIVERSE,
        "render_time": datetime.now().strftime("%H:%M:%S"),
        # Legacy context placeholders — public release no longer surfaces
        # these but the existing mobile/showcase templates still reference
        # them. Empty defaults keep rendering working until those templates
        # are rebuilt in the next phase.
        "personas": [],
        "trades": [],
        "ftmo": {"error": "Public release: positions disabled."},
    }


# ---------- routes ----------

@app.get("/about", response_class=HTMLResponse)
async def about_page(request: Request):
    """Static about / methodology / disclaimer page."""
    runs = list_runs()
    last_synced_iso = None
    if runs:
        summary_path = BIAS_CARDS_DIR / runs[0] / "run_summary.json"
        if summary_path.exists():
            try:
                last_synced_iso = datetime.fromtimestamp(
                    summary_path.stat().st_mtime
                ).isoformat(timespec="seconds")
            except Exception:
                pass
    return templates.TemplateResponse(request, "about.html", {
        "surface": _detect_surface(request),
        "run_date": runs[0] if runs else "",
        "last_synced_iso": last_synced_iso,
        "render_time": datetime.now().strftime("%H:%M:%S"),
    })


# ---------- Currency Strength Meter ----------

# Plain-language phrasing per pillar (support, headwind). Deterministic —
# no LLM. Keeps the explanation layman-friendly and consistent.
_PILLAR_PHRASE = {
    "monetary": ("relatively high interest rates", "low interest rates"),
    "growth": ("a resilient economy", "a softening economy"),
    "positioning": ("supportive investor positioning", "investors leaning against it"),
    "risk": ("the current market mood", "a risk mood working against it"),
    "commodity": ("firm commodity prices", "weak commodity prices"),
}


def _strength_blurb(c: dict) -> str:
    """Build a 1-2 sentence, jargon-free explanation from the pillar scores."""
    pills = c.get("pillars", {})
    name, label, rank = c["name"], c["label"], c["rank"]
    pos = sorted(((v, k) for k, v in pills.items() if v > 8), reverse=True)
    neg = sorted((v, k) for k, v in pills.items() if v < -8)
    parts = [f"The {name} is {label.lower()} — ranked #{rank} of the eight majors."]
    clause = []
    if pos:
        clause.append("supported by " + _PILLAR_PHRASE[pos[0][1]][0])
    if neg:
        clause.append("held back by " + _PILLAR_PHRASE[neg[0][1]][1])
    if clause:
        s = " and ".join(clause)
        parts.append(s[0].upper() + s[1:] + ".")
    tr = c.get("trend", {})
    if tr.get("label") in ("strengthening", "weakening"):
        parts.append(f"It has been {tr['label']} over recent weeks.")
    return " ".join(parts)


_PILLAR_ORDER = [
    ("monetary", "Interest Rates"), ("growth", "Growth"),
    ("positioning", "Positioning"), ("risk", "Risk Mood"),
    ("commodity", "Commodities"),
]


def _asof_date(ind: dict) -> str | None:
    a = ind.get("as_of")
    return a[:10] if a and "T" in a else a


def _display_indicators(c: dict) -> list[dict]:
    """Human-readable underlying data with correct signs/units + as-of dates."""
    ind = c.get("indicators", {})
    rows = []
    if "rate_level" in ind:
        rows.append({"label": "Short-term rate", "val": f"{ind['rate_level']['value']:.2f}%", "asof": _asof_date(ind["rate_level"])})
    if "bond_level" in ind:
        rows.append({"label": "10-year yield", "val": f"{ind['bond_level']['value']:.2f}%", "asof": _asof_date(ind["bond_level"])})
    if "unrate_level" in ind:
        rows.append({"label": "Unemployment", "val": f"{-ind['unrate_level']['value']:.1f}%", "asof": _asof_date(ind["unrate_level"])})
    if "cot_pctile" in ind:
        rows.append({"label": "Fund positioning", "val": f"{ind['cot_pctile']['value'] + 50:.0f}th pctile", "asof": _asof_date(ind["cot_pctile"])})
    if "commodity" in ind:
        v = ind["commodity"]["value"]
        rows.append({"label": "Commodity momentum", "val": f"{'+' if v >= 0 else ''}{v:.2f}σ", "asof": _asof_date(ind["commodity"])})
    if c.get("price_3m") is not None:
        v = c["price_3m"]
        rows.append({"label": "3-month move vs USD", "val": f"{'+' if v >= 0 else ''}{v:.1f}%", "asof": None})
    if "valuation" in ind:
        vz = ind["valuation"]["value"]
        tag = "stretched / expensive" if vz <= -1 else ("historically cheap" if vz >= 1 else "near fair value")
        rows.append({"label": "Valuation (vs 1-yr norm)", "val": tag, "asof": None})
    return rows


def _pillar_rows(c: dict) -> list[dict]:
    pills = c.get("pillars", {})
    return [{"label": lbl, "score": pills[k]} for k, lbl in _PILLAR_ORDER if k in pills]


# Plain-English character of each currency, for layman phrasing of the
# risk-sentiment and commodity sentences.
_CCY_CHARACTER = {
    "USD": {"risk": "haven"},
    "JPY": {"risk": "haven"},
    "CHF": {"risk": "haven"},
    "EUR": {"risk": "neutral"},
    "GBP": {"risk": "neutral"},
    "AUD": {"risk": "risk", "exports": "metals like iron ore"},
    "NZD": {"risk": "risk", "exports": "farm goods like dairy"},
    "CAD": {"risk": "risk", "exports": "oil"},
}


def _strength_explanation(c: dict) -> str:
    """A plain-English, jargon-free explanation a non-expert can follow.
    Deterministic — built straight from the pillar scores + raw data."""
    name, rank, comp = c["name"], c["rank"], c["composite"]
    pills, ind, tr = c.get("pillars", {}), c.get("indicators", {}), c.get("trend", {})
    ch = _CCY_CHARACTER.get(c["code"], {})
    s = []

    # 1. Where it stands — plain
    if rank == 1:
        where = "the strongest of the eight major currencies right now"
    elif rank == 8:
        where = "the weakest of the eight major currencies right now"
    elif rank <= 3:
        where = f"one of the stronger major currencies right now (ranked #{rank} of 8)"
    elif rank >= 6:
        where = f"one of the weaker major currencies right now (ranked #{rank} of 8)"
    else:
        where = f"middle-of-the-pack among the majors (ranked #{rank} of 8)"
    s.append(f"The {name} is {where}, with a strength score of {comp:+.0f}.")

    # 2. Interest rates — the usual main driver, in everyday terms
    m = pills.get("monetary", 0.0)
    rate = ind.get("rate_level")
    if rate is not None and m > 8:
        s.append(f"Its biggest support is interest rates: at around {rate['value']:.1f}%, it "
                 "pays more than most other major economies — and money tends to move toward "
                 "currencies that pay more.")
    elif rate is not None and m < -8:
        s.append(f"Its biggest drag is interest rates: at around {rate['value']:.1f}%, it pays "
                 "less than most other major economies, so it attracts less money than "
                 "higher-paying rivals.")

    # 3. Positioning — what big investors are doing, no jargon
    cot = ind.get("cot_pctile")
    if cot is not None and cot["value"] + 50 >= 70:
        s.append("Big global investors are betting heavily that it will rise — near their most "
                 "bullish in three years. That's a strong vote of confidence, though such "
                 "crowded bets can reverse quickly if the mood shifts.")
    elif cot is not None and cot["value"] + 50 <= 30:
        s.append("Big global investors are mostly betting against it, which adds to the pressure.")

    # 4. Risk mood — explained for the currency's character
    r = pills.get("risk", 0.0)
    if abs(r) > 10:
        if ch.get("risk") == "risk":
            s.append("It tends to do well when markets feel confident, and the mood is upbeat "
                     "right now — a tailwind." if r > 0 else
                     "It tends to struggle when markets turn cautious, and that's the mood right "
                     "now — a headwind.")
        elif ch.get("risk") == "haven":
            s.append("Investors buy it for safety when they're nervous, and current jitters are "
                     "lifting it." if r > 0 else
                     "It's a safe-haven currency that shines when investors are nervous — but "
                     "markets are fairly calm right now, which gives it less of a boost.")

    # 5. Commodities — for the commodity exporters
    cm = pills.get("commodity")
    if cm is not None and ch.get("exports"):
        if cm > 8:
            s.append(f"It also earns a lot from exporting {ch['exports']}, and firm prices for "
                     "those are giving it an extra lift.")
        elif cm < -8:
            s.append(f"It earns a lot from exporting {ch['exports']}, so weak prices for those "
                     "are weighing on it.")

    # 6. Economy — only when it clearly stands out
    g = pills.get("growth")
    if g is not None and g < -12:
        s.append("A softening economy, with unemployment creeping up, is another weight on it.")
    elif g is not None and g > 12:
        s.append("A healthy economy adds further support.")

    # 7. Direction — plain
    lbl = tr.get("label")
    if lbl == "strengthening":
        s.append("Over the past few weeks it has been steadily getting stronger.")
    elif lbl == "weakening":
        s.append("Over the past few weeks it has been gradually weakening.")
    else:
        s.append("It has held fairly steady over the past few weeks.")

    # 8. Context signals (not part of the score): valuation + price divergence
    val = (ind.get("valuation") or {}).get("value")
    if val is not None and val <= -1.0:
        s.append("One caution: after that run it now looks stretched — expensive versus its "
                 "own recent range — which raises the risk of a pullback.")
    elif val is not None and val >= 1.0:
        s.append("It's also historically cheap versus its own recent range, which can cushion "
                 "the downside.")
    if c.get("divergence") == "lagging" and c.get("price_3m") is not None:
        s.append(f"Worth noting: the price hasn't fully followed yet ({c['price_3m']:+.0f}% vs "
                 "the dollar over three months), so the fundamentals may not be entirely priced in.")
    return " ".join(s)


def _build_strength_context(request: Request) -> dict | None:
    latest = cs_load_latest()
    if not latest or not latest.get("currencies"):
        return None
    cur_map = latest["currencies"]
    ordered = sorted(cur_map.values(), key=lambda d: d.get("rank", 99))
    for c in ordered:
        c["blurb"] = _strength_blurb(c)
        c["explanation"] = _strength_explanation(c)
        c["display_indicators"] = _display_indicators(c)
        c["pillar_rows"] = _pillar_rows(c)

    history = cs_all_history()
    hist_compact = {code: [[e["date"], e["composite"]] for e in history.get(code, [])]
                    for code in cur_map}

    runs = list_runs()
    return {
        "surface": _detect_surface(request),
        "as_of": latest.get("as_of"),
        "run_date": latest.get("run_date"),
        "weights": latest.get("weights", {}),
        "risk_intensity": latest.get("risk_intensity", 0.0),
        "currencies": ordered,
        "history_json": json.dumps(hist_compact, separators=(",", ":")),
        "latest_json": json.dumps({"currencies": cur_map}, separators=(",", ":")),
        "price_strength_json": json.dumps(load_price_strength() or {}, separators=(",", ":")),
        "last_synced_iso": latest.get("as_of"),
        "run_date_nav": runs[0] if runs else "",
    }


@app.get("/strength")
async def strength_alias():
    """The meter is the homepage; keep /strength as a 301 to the canonical URL."""
    return RedirectResponse(url="/", status_code=301)


@app.get("/api/strength")
async def api_strength():
    """Full meter snapshot + history (read-only JSON)."""
    latest = cs_load_latest()
    if not latest:
        raise HTTPException(503, "Strength data not available yet")
    history = cs_all_history()
    return JSONResponse({
        "latest": latest,
        "history": {k: [[e["date"], e["composite"]] for e in v]
                    for k, v in history.items()},
    })


@app.get("/api/strength/{code}")
async def api_strength_one(code: str):
    """Single-currency detail: pillars, indicators, history."""
    latest = cs_load_latest()
    if not latest:
        raise HTTPException(503, "Strength data not available yet")
    code = code.upper()
    cur = latest.get("currencies", {}).get(code)
    if not cur:
        raise HTTPException(404, f"Unknown currency {code}")
    history = cs_all_history().get(code, [])
    return JSONResponse({"currency": cur, "history": history})


# Conventional FX base priority — the higher-priority currency is the base
# (gives EURUSD, GBPUSD, AUDUSD, USDJPY, EURGBP, CADJPY ... canonical pairs).
_PAIR_PRIORITY = ["EUR", "GBP", "AUD", "NZD", "USD", "CAD", "CHF", "JPY"]


def _canonical_pair(a: str, b: str) -> tuple[str, str]:
    return (a, b) if _PAIR_PRIORITY.index(a) < _PAIR_PRIORITY.index(b) else (b, a)


def _all_pair_slugs() -> list[str]:
    from itertools import combinations
    return [(a + b).lower() for a, b in combinations(_PAIR_PRIORITY, 2)]


def _pair_explanation(B: dict, Q: dict, diff: float, pillars: list[dict]) -> str:
    bn, qn = B["name"], Q["name"]
    strong = bn if diff >= 0 else qn
    weak = qn if diff >= 0 else bn
    s = [f"On the Macro Currency Strength Meter, the {bn} scores {B['composite']:+.0f} "
         f"and the {qn} scores {Q['composite']:+.0f} — a gap of {abs(diff):.0f} points "
         f"in favour of the {strong}."]
    big = max(pillars, key=lambda p: abs(p["gap"]), default=None)
    if big and abs(big["gap"]) >= 10:
        fav = bn if big["gap"] > 0 else qn
        s.append(f"The widest divergence is in {big['label'].lower()}, which favours the {fav}.")
    if abs(diff) < 10:
        s.append("With both currencies scoring similarly, the fundamental case here is broadly balanced.")
    else:
        s.append(f"All else equal that gap is a fundamental tailwind for the {strong} against "
                 f"the {weak} — though markets may already have priced much of it in.")
    return " ".join(s)


def _currency_ctx(request: Request, code: str) -> dict | None:
    latest = cs_load_latest()
    if not latest:
        return None
    code = code.upper()
    src = latest.get("currencies", {}).get(code)
    if not src:
        return None
    c = dict(src)
    c["explanation"] = _strength_explanation(c)
    c["display_indicators"] = _display_indicators(c)
    c["pillar_rows"] = _pillar_rows(c)
    hist = cs_all_history().get(code, [])
    pairs = []
    for other in _PAIR_PRIORITY:
        if other == code or other not in latest["currencies"]:
            continue
        oc = latest["currencies"][other]
        d = round(c["composite"] - oc["composite"], 1)
        base, quote = _canonical_pair(code, other)
        pairs.append({"slug": (base + quote).lower(), "label": f"{base}/{quote}",
                      "other": other, "diff": d, "stronger": code if d >= 0 else other})
    pairs.sort(key=lambda p: -p["diff"])
    return {
        "surface": _detect_surface(request),
        "c": c,
        "pairs": pairs,
        "run_date": latest.get("run_date"),
        "as_of": latest.get("as_of"),
        "last_synced_iso": latest.get("as_of"),
        "run_date_nav": (list_runs() or [""])[0],
        "history_json": json.dumps([[e["date"], e["composite"]] for e in hist],
                                   separators=(",", ":")),
    }


def _pair_ctx(request: Request, base: str, quote: str) -> dict | None:
    latest = cs_load_latest()
    if not latest:
        return None
    B = latest.get("currencies", {}).get(base)
    Q = latest.get("currencies", {}).get(quote)
    if not B or not Q:
        return None
    diff = round(B["composite"] - Q["composite"], 1)
    pillars = []
    for k, lbl in _PILLAR_ORDER:
        if k in B.get("pillars", {}) or k in Q.get("pillars", {}):
            bv = B["pillars"].get(k)
            qv = Q["pillars"].get(k)
            pillars.append({"label": lbl, "b": bv, "q": qv,
                            "gap": round((bv or 0) - (qv or 0), 1)})
    return {
        "surface": _detect_surface(request),
        "base": B, "quote": Q, "diff": diff, "pillars": pillars,
        "stronger": B if diff >= 0 else Q,
        "explanation": _pair_explanation(B, Q, diff, pillars),
        "run_date": latest.get("run_date"),
        "as_of": latest.get("as_of"),
        "last_synced_iso": latest.get("as_of"),
        "run_date_nav": (list_runs() or [""])[0],
    }


@app.get("/currency/{code}", response_class=HTMLResponse)
async def currency_page(request: Request, code: str):
    ctx = _currency_ctx(request, code)
    if not ctx:
        raise HTTPException(404, f"Unknown currency '{code}'")
    return templates.TemplateResponse(request, "currency_page.html", ctx)


@app.get("/pair/{pair}")
async def pair_page(request: Request, pair: str):
    p = pair.upper().replace("/", "")
    if len(p) != 6:
        raise HTTPException(404, "Pair must be 6 letters, e.g. eurusd")
    a, b = p[:3], p[3:]
    if a not in _PAIR_PRIORITY or b not in _PAIR_PRIORITY or a == b:
        raise HTTPException(404, f"Unknown pair '{pair}'")
    base, quote = _canonical_pair(a, b)
    if base + quote != p:  # normalise to canonical URL
        return RedirectResponse(url=f"/pair/{(base + quote).lower()}", status_code=301)
    ctx = _pair_ctx(request, base, quote)
    if not ctx:
        raise HTTPException(404, f"Pair data unavailable for '{pair}'")
    return templates.TemplateResponse(request, "pair_page.html", ctx)


# ---------- Research / journal (file-based blog for SEO) ----------

_RESEARCH_DIR = PROJECT_ROOT / "content" / "research"


def _load_research_posts(include_unpublished: bool = False) -> list[dict]:
    """Read markdown posts from content/research/*.md with `--- yaml ---` front
    matter (title, date, summary). Newest first.

    Posts dated in the future are treated as SCHEDULED: hidden from the index,
    sitemap and static build (so they don't flood), but still reachable by
    direct URL for preview. This powers the every-2-days drip — each 4-hourly
    rebuild reveals any post whose date has arrived.
    """
    posts: list[dict] = []
    if not _RESEARCH_DIR.exists():
        return posts
    for p in _RESEARCH_DIR.glob("*.md"):
        try:
            raw = p.read_text(encoding="utf-8")
        except OSError:
            continue
        meta, body = {}, raw
        if raw.lstrip().startswith("---"):
            parts = raw.split("---", 2)
            if len(parts) >= 3:
                try:
                    meta = _yaml.safe_load(parts[1]) or {}
                except Exception:
                    meta = {}
                body = parts[2]
        faq = meta.get("faq") if isinstance(meta.get("faq"), list) else []
        posts.append({
            "slug": str(meta.get("slug") or p.stem),
            "title": str(meta.get("title") or p.stem),
            "date": str(meta.get("date") or ""),
            "updated": str(meta.get("updated") or meta.get("date") or ""),
            "summary": str(meta.get("summary") or ""),
            "keyword": str(meta.get("keyword") or ""),
            "faq": faq,
            "body_md": body.strip(),
        })
    if not include_unpublished:
        from datetime import date as _dt_date
        today = _dt_date.today().isoformat()
        posts = [p for p in posts if (p["date"] or "0000-00-00") <= today]
    posts.sort(key=lambda x: x["date"], reverse=True)
    return posts


@app.get("/research", response_class=HTMLResponse)
async def research_index(request: Request):
    return templates.TemplateResponse(request, "research_index.html", {
        "surface": _detect_surface(request),
        "posts": _load_research_posts(),
    })


@app.get("/research/{slug}", response_class=HTMLResponse)
async def research_post(request: Request, slug: str):
    post = next((p for p in _load_research_posts(include_unpublished=True) if p["slug"] == slug), None)
    if not post:
        raise HTTPException(404, "Article not found")
    post = dict(post)
    post["html"] = _render_markdown_blog(post["body_md"])
    return templates.TemplateResponse(request, "research_post.html", {
        "surface": _detect_surface(request), "post": post,
    })


@app.get("/privacy", response_class=HTMLResponse)
async def privacy_page(request: Request):
    return templates.TemplateResponse(request, "privacy.html", {
        "surface": _detect_surface(request),
    })


@app.get("/sitemap.xml")
async def sitemap():
    base = "https://piptheory.com"
    urls = ["/", "/about", "/research", "/privacy"]
    urls += [f"/research/{p['slug']}" for p in _load_research_posts()]
    urls += [f"/currency/{c.lower()}" for c in _PAIR_PRIORITY]
    urls += [f"/pair/{slug}" for slug in _all_pair_slugs()]
    body = ['<?xml version="1.0" encoding="UTF-8"?>',
            '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
    body += [f"  <url><loc>{base}{u}</loc></url>" for u in urls]
    body.append("</urlset>")
    return Response(content="\n".join(body), media_type="application/xml")


@app.get("/", response_class=HTMLResponse)
async def index(request: Request):
    """Homepage = the Macro Currency Strength Meter (the hero)."""
    ctx = _build_strength_context(request)
    if ctx:
        return templates.TemplateResponse(request, "dashboard_strength.html", ctx)
    return HTMLResponse(
        "<h1>Macro Currency Strength Meter</h1><p>Data is being generated — "
        "check back shortly.</p>", status_code=503)


# The LLM "Research Desk" (per-instrument bull/bear/judge) is RETIRED to cut
# spend and is hidden from the public. Old /run/* URLs redirect to the meter.
@app.get("/run/{date}")
@app.get("/run")
async def run_page(date: str | None = None):
    return RedirectResponse(url="/", status_code=301)


# ---------- API: recent events log (READ-ONLY in public release) ----------

@app.get("/api/recent-events")
async def api_recent_events_list():
    """Return all logged events, most recent first. Read-only on the
    public site — write/delete endpoints removed when the project
    pivoted to public research only."""
    events = load_recent_events()
    return JSONResponse({"events": [
        {
            "date": e.date.isoformat(),
            "days_ago": e.days_ago,
            "headline": e.headline,
            "impact": e.impact,
            "notes": e.notes,
            "relevance": e.relevance,
            "affects": e.affects or [],
        }
        for e in events
    ]})


# ---------- API: reasoning + brief (read-only) ----------

@app.get("/api/reasoning/{symbol}")
async def api_reasoning(symbol: str, date: str | None = None):
    """Return all agent outputs for an instrument so the dashboard can
    render the 'Why?' detail panel without baking everything into the
    initial page render.
    """
    runs = list_runs()
    target = date if date and date in runs else (runs[0] if runs else None)
    if not target:
        raise HTTPException(404, "No runs available")
    run = load_run(target)
    if not run:
        raise HTTPException(500, "Could not load run")
    sym = symbol.upper()
    bias_obj = next((b for b in run.instrument_biases if b.instrument == sym), None)
    co = run.council.get(sym)
    fc = run.tradability.get(sym)
    thesis = thesis_tracker.status_for(sym)
    history = score_history.summary_for(sym, n=14)
    return JSONResponse({
        "symbol": sym,
        "name": display_label(sym),
        "thesis": thesis,
        "history": history,
        "strategist_md": bias_obj.raw_section if bias_obj else "",
        "strategist_md_rendered": _render_markdown(bias_obj.raw_section) if bias_obj else "",
        "judge_md": co.judge if co else "",
        "judge_md_rendered": _render_markdown(co.judge) if co else "",
        "bull_md": co.bull if co else "",
        "bull_md_rendered": _render_markdown(co.bull) if co else "",
        "bear_md": co.bear if co else "",
        "bear_md_rendered": _render_markdown(co.bear) if co else "",
        "filter_md": fc.raw if fc else "",
        "filter_md_rendered": _render_markdown(fc.raw) if fc else "",
    })


@app.get("/api/brief")
async def api_brief(date: str | None = None):
    """Return the rendered PM brief for a run. Used by the mobile brief sheet."""
    runs = list_runs()
    target = date if date and date in runs else (runs[0] if runs else None)
    if not target:
        return JSONResponse({"html": ""})
    run = load_run(target)
    return JSONResponse({"html": _render_markdown(run.layer5_pm_brief) if run and run.layer5_pm_brief else ""})


# ---------- Personal-only routes removed in public release ----------
#
# The following used to live here:
#   POST /api/chat                       — personalised analyst chat
#   GET  /api/positions                  — list active + recent closed
#   POST /api/positions                  — record a trade
#   POST /api/positions/{id}/close       — mark a trade closed
#   POST /api/positions/{id}/note        — add a note
#   PATCH /api/positions/{id}            — edit a trade
#   POST /api/positions/{id}/stop        — move the stop
#   DELETE /api/positions/{id}           — delete a trade
#   POST /api/run                        — trigger a fresh pipeline run
#
# They were removed when the project pivoted to a public read-only research
# site. The pipeline runs on a schedule (07:00 UTC via Windows Task
# Scheduler — see scripts/install_scheduled_task.ps1) instead of being
# user-triggered. See git history if you ever need the implementations
# back for a private fork.

_LOG_PATH = PROJECT_ROOT / "logs" / "bias_engine.log"

# Matches the timestamp written by run_daily.bat's "Run started DATE TIME"
# header line, which uses Windows "DD/MM/YYYY  H:MM:SS.cc" format.
_LOG_RUN_STARTED_RE = re.compile(
    r"Run started\s+(\d{1,2}/\d{1,2}/\d{4})\s+(\d{1,2}:\d{2}:\d{2})"
)


def _find_recent_run_start(tail: list[str]) -> datetime | None:
    """Walk a log tail backward for the most recent 'Run started' line.

    Used when we're rendering an in-progress run that this uvicorn instance
    didn't launch — e.g., the user clicked Run, server got restarted, the
    pipeline kept going. We can still time it by reading the start timestamp
    from the log header that run_daily.bat writes.
    """
    for ln in reversed(tail):
        m = _LOG_RUN_STARTED_RE.search(ln)
        if not m:
            continue
        date_str, time_str = m.groups()
        for fmt in ("%d/%m/%Y %H:%M:%S", "%m/%d/%Y %H:%M:%S"):
            try:
                return datetime.strptime(f"{date_str} {time_str}", fmt)
            except ValueError:
                continue
    return None


def _detect_running_pipeline() -> dict | None:
    """Return run-in-progress info if a pipeline is currently running.

    Two detection paths:
      1. Internal — _run_state['pid'] is alive. Cheap, exact start time.
      2. Log-based — log file modified within last 5 min AND the tail
         doesn't show a 'Run finished'. Catches runs the server didn't
         start (cron task, terminal, or pre-restart). 5-minute threshold
         is wide enough that slow agent calls (DeepSeek can take 3 min)
         don't false-negative.
    """
    # 1. Internal
    pid = _run_state.get("pid")
    if pid and _is_run_alive(pid):
        started = _run_state.get("started_at")
        return {
            "pid": pid,
            "started_at": started.isoformat() if started else None,
            "source": "internal",
        }

    # 2. Log-based
    if not _LOG_PATH.exists():
        return None
    mtime = datetime.fromtimestamp(_LOG_PATH.stat().st_mtime)
    age_seconds = (datetime.now() - mtime).total_seconds()
    if age_seconds > 300:
        return None
    tail = _read_log_tail(30)
    # Most-recent 'Run finished' line means we're past the run, not in it.
    if any("Run finished" in ln for ln in tail[-10:]):
        return None
    # An agent call must be in flight (or some layer activity)
    if not any(
        ("openrouter_call_start" in ln or "run_agent_start" in ln or "layer" in ln)
        for ln in tail
    ):
        return None
    start_time = _find_recent_run_start(_read_log_tail(800))
    return {
        "pid": None,
        "started_at": start_time.isoformat() if start_time else None,
        "source": "external",
    }


# Pipeline stages, in order, with friendly labels. Used to render progress.
_STAGES = [
    ("layer1_inflation_start", "Layer 1 — Inflation Tracker"),
    ("layer1_positioning_start", "Layer 1 — Positioning Analyst"),
    ("layer1_fed_start", "Layer 1 — Fed-Watcher"),
    ("layer2_strategist_start", "Layer 2 — Strategist (synthesis)"),
    ("layer3_contrarian_start", "Layer 3 — Contrarian (red team)"),
    ("layer4_council_start", "Layer 4 — Bias Council debate"),
    ("layer4b_filter_start", "Layer 4b — Tradability Filter"),
    ("layer5_pm_start", "Layer 5 — PM Brief"),
]


def _read_log_tail(n: int = 50) -> list[str]:
    if not _LOG_PATH.exists():
        return []
    try:
        with _LOG_PATH.open("r", encoding="utf-8", errors="replace") as f:
            lines = f.readlines()
        return [ln.rstrip("\n") for ln in lines[-n:]]
    except Exception:
        return []


def _detect_current_stage(log_tail: list[str]) -> dict:
    """Find the most recent stage start line in the log.

    Parallel-aware: if a parallel layer is in flight (start logged, complete
    not yet logged), report it as a single coherent stage with an in-flight
    count rather than the most recent individual agent (which jumps between
    threads under parallel mode).
    """
    last_event_line = next((ln for ln in reversed(log_tail) if "[info" in ln), None)

    # ---- Parallel-block detection ----
    parallel_blocks = [
        ("layer1_parallel_start", "layer1_parallel_complete",
         "Layer 1 — Specialists (3 in parallel)"),
        ("layer4_parallel_start", "layer4_parallel_complete",
         "Layer 4 + 4b — Council & Filter (parallel)"),
    ]
    for start_marker, end_marker, label in parallel_blocks:
        # Most recent occurrence of start, with no following complete
        last_start_idx = -1
        last_end_idx = -1
        for i, ln in enumerate(log_tail):
            if start_marker in ln:
                last_start_idx = i
            if end_marker in ln:
                last_end_idx = i
        if last_start_idx >= 0 and last_end_idx < last_start_idx:
            # In flight. Count agent_start minus agent_complete since the
            # parallel block started — gives the user a real progress feel.
            since_start = log_tail[last_start_idx:]
            starts = sum(1 for ln in since_start if "run_agent_start" in ln)
            completes = sum(1 for ln in since_start if "run_agent_complete" in ln)
            in_flight = max(0, starts - completes)
            stage = f"{label} · {completes} done · {in_flight} in flight"
            return {"stage": stage, "last_event_line": last_event_line}

    # ---- Fallback: serial-stage detection ----
    stage_label = "Starting…"
    instrument: str | None = None
    agent: str | None = None
    for ln in reversed(log_tail):
        for marker, label in _STAGES:
            if marker in ln:
                stage_label = label
                if "instrument=" in ln:
                    try:
                        instrument = ln.split("instrument=")[1].split()[0]
                    except Exception:
                        pass
                if "agent=" in ln:
                    try:
                        agent = ln.split("agent=")[1].split()[0]
                    except Exception:
                        pass
                if instrument:
                    stage_label = f"{stage_label} · {instrument}"
                if agent and "agent_start" in ln:
                    stage_label = f"{stage_label} ({agent})"
                return {"stage": stage_label, "last_event_line": last_event_line}
    return {"stage": stage_label, "last_event_line": last_event_line}


def _latest_run_meta() -> dict | None:
    """Read most recent completed run's summary."""
    runs = list_runs()
    if not runs:
        return None
    summary_path = PROJECT_ROOT / "bias_cards" / runs[0] / "run_summary.json"
    if not summary_path.exists():
        return {"run_date": runs[0], "completed_at": None, "cost_usd": None}
    try:
        data = json.loads(summary_path.read_text(encoding="utf-8"))
        mtime = datetime.fromtimestamp(summary_path.stat().st_mtime)
        return {
            "run_date": data.get("run_date", runs[0]),
            "completed_at": mtime.isoformat(timespec="seconds"),
            "cost_usd": data.get("total_cost_usd"),
        }
    except Exception:
        return {"run_date": runs[0], "completed_at": None, "cost_usd": None}


@app.get("/api/run/status")
async def api_run_status():
    latest = _latest_run_meta()

    detected = _detect_running_pipeline()
    if not detected:
        # No internal PID and no log activity — clear the stale internal state
        # so a future button-press doesn't think a run is already going.
        if _run_state.get("pid"):
            _run_state["pid"] = None
            _run_state["started_at"] = None
        return JSONResponse({"running": False, "latest": latest})

    started_iso = detected.get("started_at")
    started_dt: datetime | None = None
    if started_iso:
        try:
            started_dt = datetime.fromisoformat(started_iso)
        except ValueError:
            started_dt = None
    elapsed_s = (
        int((datetime.now() - started_dt).total_seconds())
        if started_dt else 0
    )
    est_total = 900
    pct = min(95, int(elapsed_s / est_total * 100)) if elapsed_s else 0
    stage_info = _detect_current_stage(_read_log_tail(200))

    return JSONResponse({
        "running": True,
        "pid": detected.get("pid"),
        "source": detected.get("source"),
        "started_at": started_iso,
        "elapsed_seconds": elapsed_s,
        "estimated_total_seconds": est_total,
        "estimated_pct": pct,
        "stage": stage_info["stage"],
        "last_event_line": stage_info["last_event_line"],
        "latest": latest,
    })


@app.get("/api/run/log")
async def api_run_log(lines: int = 30):
    return JSONResponse({"lines": _read_log_tail(lines)})


# ---------- admin: manual sync (NOT exposed to public) -----------------------
#
# Auth model:
#   * A single shared secret token grants admin access.
#   * Token source priority:
#       1. env PIPTHEORY_ADMIN_TOKEN  (preferred for production)
#       2. state/admin_token.txt      (auto-generated on first start if env
#                                      not set; gitignored via state/* rule)
#   * Cookie pt_admin holds the token verbatim. SameSite=Strict + HttpOnly
#     blocks CSRF and JS exfiltration. Cookie is set with Secure when the
#     request arrived over HTTPS (Tailscale Serve terminates TLS upstream).
#
# Surface model:
#   * Routes live under /admin/* and are NOT linked from any public template,
#     /about, footer, robots.txt, sitemap, etc. The public site has no
#     awareness that admin exists.
#   * /admin returns 404 (not 401) to anonymous visitors. The login form is
#     served from the SAME path when the user POSTs the right token. This way
#     scanners can't fingerprint the admin endpoint by status code alone.
#   * Robots.txt should disallow /admin (added separately).
#
# Run model:
#   * /admin/run POST spawns scripts/run_daily.bat via subprocess in a new
#     process group so it survives uvicorn restarts and the parent doesn't
#     block. PID is tracked in _run_state and surfaced via /admin/status
#     for the run-in-progress UI.

_ADMIN_TOKEN_FILE = PROJECT_ROOT / "state" / "admin_token.txt"


_FALLBACK_ADMIN_TOKEN = os.environ.get(
    "PIPTHEORY_ADMIN_TOKEN_FALLBACK",
    "pt-fallback-8Xk2mR9vLp4nWq7yB6cJ3hT5gE1sA0dF",  # hardcoded fallback for Render
).strip()


def _load_or_create_admin_token() -> str:
    """Return the admin token.

    Priority:
      0. DEBUG HARDCODE — will be removed once env-var works on Render
      1. env PIPTHEORY_ADMIN_TOKEN
      2. env PIPTHEORY_ADMIN_TOKEN_FALLBACK (hardcoded / env fallback for Render)
      3. state/admin_token.txt
      4. generate 32-char URL-safe token, write to file, log path to stderr
    """
    # DEBUG: return hardcoded token regardless of env — remove once
    # PIPTHEORY_ADMIN_TOKEN is reliably set on Render
    return "pt-fallback-8Xk2mR9vLp4nWq7yB6cJ3hT5gE1sA0dF"

    env_token = os.environ.get("PIPTHEORY_ADMIN_TOKEN", "").strip()
    if env_token:
        return env_token
    if _FALLBACK_ADMIN_TOKEN:
        return _FALLBACK_ADMIN_TOKEN
    if _ADMIN_TOKEN_FILE.exists():
        try:
            tok = _ADMIN_TOKEN_FILE.read_text(encoding="utf-8").strip()
            if tok:
                return tok
        except Exception:
            pass
    tok = secrets.token_urlsafe(32)
    _ADMIN_TOKEN_FILE.parent.mkdir(parents=True, exist_ok=True)
    _ADMIN_TOKEN_FILE.write_text(tok + "\n", encoding="utf-8")
    print(
        f"[piptheory.admin] generated new admin token at {_ADMIN_TOKEN_FILE}\n"
        f"                  paste this into the /admin login form.",
        file=sys.stderr,
    )
    return tok


_ADMIN_TOKEN = _load_or_create_admin_token()
_ADMIN_COOKIE = "pt_admin"


def _is_admin(request: Request) -> bool:
    """Constant-time check on the auth cookie."""
    cookie_val = request.cookies.get(_ADMIN_COOKIE, "")
    if not cookie_val or not _ADMIN_TOKEN:
        return False
    return secrets.compare_digest(cookie_val, _ADMIN_TOKEN)


def _is_secure(request: Request) -> bool:
    """Heuristic: is this connection HTTPS?

    Tailscale Serve terminates TLS upstream, so we honor X-Forwarded-Proto.
    Direct localhost access stays HTTP and Secure cookies wouldn't be sent.
    """
    if request.url.scheme == "https":
        return True
    fwd = request.headers.get("x-forwarded-proto", "").lower()
    return "https" in fwd


# In-memory tracker for the most recent admin-triggered pipeline run.
# Lost on uvicorn restart; that's fine — _detect_running_pipeline() falls
# back to log-based detection so the UI stays accurate across restarts.
_run_state: dict = {"pid": None, "started_at": None}


def _is_run_alive(pid: int | None) -> bool:
    """True if the tracked PID is still running. Cheap, no dependencies."""
    if not pid:
        return False
    if sys.platform == "win32":
        # tasklist exit 0 + PID present in output => alive.
        try:
            out = subprocess.run(
                ["tasklist", "/FI", f"PID eq {pid}", "/NH"],
                capture_output=True, text=True, timeout=3,
            )
            return str(pid) in (out.stdout or "")
        except Exception:
            return False
    try:
        os.kill(pid, 0)
        return True
    except (OSError, ProcessLookupError):
        return False


def _spawn_pipeline_run() -> int | None:
    """Start the pipeline in a detached process. Returns PID.

    Uses scripts/run_daily.sh on Linux and run_daily.bat on Windows so
    each platform gets the correct shell syntax, paths and venv activation.

    Returns None if a run is already in progress (no double-start).
    """
    detected = _detect_running_pipeline()
    if detected:
        return None

    if sys.platform == "win32":
        script = PROJECT_ROOT / "scripts" / "run_daily.bat"
        if not script.exists():
            raise RuntimeError(f"run_daily.bat not found at {script}")
        # DETACHED_PROCESS (0x08) + CREATE_NEW_PROCESS_GROUP (0x200) so the
        # child survives if uvicorn exits. CREATE_NO_WINDOW (0x08000000)
        # suppresses the console flash that .bat normally creates.
        flags = 0x00000008 | 0x00000200 | 0x08000000
        proc = subprocess.Popen(
            ["cmd.exe", "/c", str(script)],
            cwd=str(PROJECT_ROOT),
            creationflags=flags,
            stdin=subprocess.DEVNULL,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            close_fds=True,
        )
    else:
        script = PROJECT_ROOT / "scripts" / "run_daily.sh"
        if not script.exists():
            raise RuntimeError(f"run_daily.sh not found at {script}")
        proc = subprocess.Popen(
            ["bash", str(script)],
            cwd=str(PROJECT_ROOT),
            stdin=subprocess.DEVNULL,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            start_new_session=True,
            close_fds=True,
        )
    _run_state["pid"] = proc.pid
    _run_state["started_at"] = datetime.now()
    return proc.pid


def _admin_context(request: Request) -> dict:
    """Common template context for admin dashboard."""
    detected = _detect_running_pipeline()
    return {
        "request": request,
        "static_version": _STATIC_VERSION,
        "surface": "desktop",  # admin is desktop-only
        "running": bool(detected),
        "run_info": detected,
        "latest": _latest_run_meta(),
        "log_tail": _read_log_tail(60),
        "stage": (
            _detect_current_stage(_read_log_tail(200))["stage"]
            if detected else None
        ),
    }


@app.get("/admin", response_class=HTMLResponse)
async def admin_root(request: Request):
    """If authenticated, show dashboard; else show login form.

    Both states return 200 from the same path so anonymous scanners can't
    distinguish 'admin exists, you're not logged in' from 'admin exists,
    you are logged in'. The login template is deliberately bland.
    """
    if _is_admin(request):
        return templates.TemplateResponse(
            request, "admin_dashboard.html", _admin_context(request),
        )
    return templates.TemplateResponse(request, "admin_login.html", {
        "request": request,
        "static_version": _STATIC_VERSION,
        "surface": "desktop",
        "error": None,
    })


@app.post("/admin", response_class=HTMLResponse)
async def admin_login(request: Request, token: str = Form(...)):
    """Validate token, set cookie, redirect to /admin (now authenticated).

    Reuses the /admin path for login POST so we don't expose a separate
    /admin/login endpoint that scanners could distinguish.
    """
    if not secrets.compare_digest(token.strip(), _ADMIN_TOKEN):
        # Same response shape as anonymous GET — generic login form with
        # an "invalid token" hint. Don't 401; don't time-leak failure.
        return templates.TemplateResponse(request, "admin_login.html", {
            "request": request,
            "static_version": _STATIC_VERSION,
            "surface": "desktop",
            "error": "Invalid token.",
        }, status_code=200)
    response = RedirectResponse(url="/admin", status_code=303)
    response.set_cookie(
        _ADMIN_COOKIE,
        _ADMIN_TOKEN,
        max_age=60 * 60 * 24 * 7,  # 7-day session
        httponly=True,
        samesite="strict",
        secure=_is_secure(request),
        path="/admin",  # only sent on /admin/* — never leaks to public routes
    )
    return response


@app.post("/admin/logout")
async def admin_logout(request: Request):
    response = RedirectResponse(url="/admin", status_code=303)
    response.delete_cookie(_ADMIN_COOKIE, path="/admin")
    return response


@app.post("/admin/run")
async def admin_run(request: Request):
    """Trigger the daily pipeline. Returns JSON for the dashboard's fetch()."""
    if not _is_admin(request):
        # Return 404 not 401/403 — preserves the 'admin doesn't exist'
        # illusion for unauthenticated POSTs.
        raise HTTPException(status_code=404, detail="Not Found")
    try:
        pid = _spawn_pipeline_run()
    except Exception as e:
        return JSONResponse({"ok": False, "error": str(e)}, status_code=500)
    if pid is None:
        return JSONResponse({
            "ok": False,
            "error": "A run is already in progress.",
        }, status_code=409)
    return JSONResponse({"ok": True, "pid": pid})


@app.get("/admin/status")
async def admin_status(request: Request):
    """JSON status for the admin dashboard's polling loop."""
    if not _is_admin(request):
        raise HTTPException(status_code=404, detail="Not Found")
    detected = _detect_running_pipeline()
    latest = _latest_run_meta()
    if not detected:
        if _run_state.get("pid"):
            _run_state["pid"] = None
            _run_state["started_at"] = None
        return JSONResponse({"running": False, "latest": latest})
    started_iso = detected.get("started_at")
    started_dt: datetime | None = None
    if started_iso:
        try:
            started_dt = datetime.fromisoformat(started_iso)
        except ValueError:
            pass
    elapsed_s = (
        int((datetime.now() - started_dt).total_seconds()) if started_dt else 0
    )
    est_total = 900
    pct = min(95, int(elapsed_s / est_total * 100)) if elapsed_s else 0
    stage_info = _detect_current_stage(_read_log_tail(200))
    return JSONResponse({
        "running": True,
        "pid": detected.get("pid"),
        "source": detected.get("source"),
        "started_at": started_iso,
        "elapsed_seconds": elapsed_s,
        "estimated_total_seconds": est_total,
        "estimated_pct": pct,
        "stage": stage_info["stage"],
        "last_event_line": stage_info["last_event_line"],
        "latest": latest,
    })


@app.get("/admin/log")
async def admin_log(request: Request, lines: int = 80):
    if not _is_admin(request):
        raise HTTPException(status_code=404, detail="Not Found")
    return JSONResponse({"lines": _read_log_tail(lines)})


# ---------- robots.txt: explicitly disallow /admin -----------

@app.get("/robots.txt")
async def robots():
    body = (
        "User-agent: *\n"
        "Disallow: /admin\n"
        "Disallow: /api/\n"
        "Allow: /\n"
        "\n"
        "Sitemap: https://piptheory.com/sitemap.xml\n"
    )
    return HTMLResponse(content=body, media_type="text/plain")


# ---------- ads.txt: authorise Google AdSense to sell our inventory ----------

@app.get("/ads.txt")
async def ads_txt():
    pub = ((_AD_CONFIG or {}).get("adsense_publisher_id") or "").strip()
    # ads.txt uses the bare "pub-..." form (no "ca-" prefix).
    pub_id = pub.replace("ca-pub-", "pub-") if pub.startswith("ca-pub-") else pub
    if not pub_id.startswith("pub-"):
        return HTMLResponse(content="", media_type="text/plain")
    body = f"google.com, {pub_id}, DIRECT, f08c47fec0942fa0\n"
    return HTMLResponse(content=body, media_type="text/plain")


# ---------- markdown rendering helper for templates ----------

import markdown as md_lib  # noqa: E402

_md = md_lib.Markdown(extensions=["fenced_code", "tables", "nl2br", "sane_lists"])

# Blog/research posts contain rich raw HTML + inline SVG graphics. Use a
# dedicated instance WITHOUT nl2br (which would inject <br> into multi-line
# markup) and WITH attr_list (so authors can attach classes/ids). Raw HTML
# blocks pass through verbatim — graphics must be wrapped in a block-level
# <div class="pt-..."> (col 0, blank lines around it) to be preserved cleanly.
_md_blog = md_lib.Markdown(extensions=["fenced_code", "tables", "sane_lists", "attr_list"])

# ── Section-header pre-processor for card content ─────────────────────────
# LLM output uses labels like "PRIMARY DRIVER:", "SUPPORTING EVIDENCE:" etc.
# as plain text. Convert them to markdown ### headers so the CSS can style
# them as proper section dividers instead of rendering as a wall of text.

_SECTION_HEADER_RE = re.compile(
    r"^(PRIMARY\s+DRIVER|SUPPORTING\s+EVIDENCE|CATALYST|KEY\s+RISKS?"
    r"|MECHANISM|INVALIDATION(?:\s+CONDITIONS?)?|PROBABILITY\s+DECOMPOSITION"
    r"|CONCLUSION|SUMMARY|KEY\s+ARGUMENTS?|COUNTER[\s-]?ARGUMENTS?"
    r"|RISK\s+FACTORS?|TRADE\s+EXPRESSION|CONTRARIAN\s+ENGAGEMENT"
    r"|NARRATIVE\s+SUMMARY|CONTRADICTIONS(?:\s*/\s*TENSIONS)?)\s*:?\s*$",
    re.IGNORECASE,
)
_SECTION_INLINE_RE = re.compile(
    r"^(PRIMARY\s+DRIVER|SUPPORTING\s+EVIDENCE|CATALYST|KEY\s+RISKS?"
    r"|MECHANISM|INVALIDATION(?:\s+CONDITIONS?)?|CONTRARIAN\s+ENGAGEMENT"
    r"|NARRATIVE\s+SUMMARY|CONTRADICTIONS(?:\s*/\s*TENSIONS)?)\s*:\s*(.+)$",
    re.IGNORECASE,
)


def _format_analysis_sections(text: str) -> str:
    """Convert LLM section labels into proper markdown ### headers."""
    if not text:
        return ""
    lines = text.split("\n")
    out: list[str] = []
    for line in lines:
        s = line.strip()
        m = _SECTION_HEADER_RE.match(s)
        if m:
            out.append("")
            out.append(f"### {m.group(1).strip().title()}")
            out.append("")
            continue
        m2 = _SECTION_INLINE_RE.match(s)
        if m2:
            out.append("")
            out.append(f"### {m2.group(1).strip().title()}")
            out.append("")
            out.append(m2.group(2).strip())
            continue
        out.append(line)
    return "\n".join(out)


def _render_markdown(text: str) -> str:
    if not text:
        return ""
    stripped = text.strip()
    # Defensive: if the whole content is wrapped in a single code fence
    # (LLMs sometimes do this even when not asked), peel it. Otherwise
    # markdown renders the entire brief as one <pre> block that doesn't
    # wrap on mobile.
    if stripped.startswith("```") and stripped.rstrip().endswith("```"):
        lines = stripped.split("\n")
        if len(lines) >= 2 and lines[0].startswith("```") and lines[-1].strip() == "```":
            stripped = "\n".join(lines[1:-1])
    _md.reset()
    return _md.convert(stripped)


def _render_markdown_blog(text: str) -> str:
    """Render a research/blog post: standard markdown + raw HTML/SVG graphics
    preserved verbatim (no nl2br). Used by /research/{slug}."""
    if not text:
        return ""
    stripped = text.strip()
    if stripped.startswith("```") and stripped.rstrip().endswith("```"):
        lines = stripped.split("\n")
        if len(lines) >= 2 and lines[0].startswith("```") and lines[-1].strip() == "```":
            stripped = "\n".join(lines[1:-1])
    _md_blog.reset()
    return _md_blog.convert(stripped)


templates.env.filters["markdown"] = _render_markdown
